# Generated by Django 4.1.2 on 2022-11-20 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judgeme', '0014_jmuser_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='artist_name',
            field=models.CharField(default='artist_name_placeholder_text', max_length=256),
            preserve_default=False,
        ),
    ]
